name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env: 
  TEST: 123
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo $TEST
      env: 
        TEST: asdf
